fix: only insert into country_latest_data if there is something to insert
this has caused mysterious `(node:4663) UnhandledPromiseRejectionWarning:
Error: The query is empty` warnings for quite some time now, and in Node
16 these actually lead to server restarts